<?php

namespace integration\Models;

use A17\Twill\Models\Behaviors\HasTranslation;
use A17\Twill\Tests\Integration\TestCase;

class TranslatableModelTest extends TestCase
{
    private \A17\Twill\Tests\Integration\Anonymous\AnonymousModule $module;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->module = \A17\Twill\Tests\Integration\Anonymous\AnonymousModule::make('cogs', app())
            ->withFields([
                'title' => ['translatable' => true],
            ])
            ->boot();
    }

    public function testHasActiveTranslationWithoutArgument(): void
    {
        /** @var HasTranslation $module */
        $module = $this->module->getRepository()->create([
            'title' => ['en' => 'English title'],
        ]);

        $this->assertTrue($module->hasActiveTranslation());
        $this->assertTrue($module->hasActiveTranslation('en'));
    }

    public function testHasActiveTranslationWithArgument(): void
    {
        /** @var HasTranslation $module */
        $module = $this->module->getRepository()->create([
            'title' => ['en' => 'English title', 'fr' => 'French title'],
            'active' => ['en' => true, 'fr' => false],
        ]);

        $this->assertFalse($module->hasActiveTranslation('fr'));
        $this->assertTrue($module->hasActiveTranslation('en'));
    }
}
