name: On Demand Formatting
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Format
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/format')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TWILL_PAT_TOKEN }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write *.js .*.{js,yml} frontend/**/*.{js,vue,scss}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
